### ISSUE TITLE
error in discord 

### ISSUE THREAD

**Issue by themeswordpress** [vxunderground/ThreatIntelligenceDiscordBot#13]
Traceback (most recent call last):
  File "c:\Users\OMEN\Desktop\ThreatIntelligenceDiscordBot-main (1)\ThreatIntelligenceDiscordBot-main\Source\DiscordIntelBot.py", line 198, in <module>
    main()
  File "c:\Users\OMEN\Desktop\ThreatIntelligenceDiscordBot-main (1)\ThreatIntelligenceDiscordBot-main\Source\DiscordIntelBot.py", line 187, in main
    handle_rss_feed_list(details["source"], details["hook"])
  File "c:\Users\OMEN\Desktop\ThreatIntelligenceDiscordBot-main (1)\ThreatIntelligenceDiscordBot-main\Source\DiscordIntelBot.py", line 163, in handle_rss_feed_list
    process_source(get_news_from_rss, rss_feed, hook)
  File "c:\Users\OMEN\Desktop\ThreatIntelligenceDiscordBot-main (1)\ThreatIntelligenceDiscordBot-main\Source\DiscordIntelBot.py", line 157, in process_source
    send_messages(hook, processed_articles, new_raw_articles)
  File "c:\Users\OMEN\Desktop\ThreatIntelligenceDiscordBot-main (1)\ThreatIntelligenceDiscordBot-main\Source\DiscordIntelBot.py", line 143, in send_messages
    hook.send(embeds=messages[i : i + batch_size])
  File "C:\Users\OMEN\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\webhook.py", line 989, in send
    return self._adapter.execute_webhook(wait=wait, file=file, files=files, payload=payload)
  File "C:\Users\OMEN\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\webhook.py", line 164, in execute_webhook
    maybe_coro = self.request('POST', url, multipart=multipart, payload=data, files=files_to_pass)
  File "C:\Users\OMEN\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\webhook.py", line 363, in request
    raise HTTPException(r, response)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.1.url: Not a well formed URL.
Exception ignored in atexit callback: <function clean_up_and_close at 0x00000239FF611CF0>
Traceback (most recent call last):
  File "c:\Users\OMEN\Desktop\ThreatIntelligenceDiscordBot-main (1)\ThreatIntelligenceDiscordBot-main\Source\DiscordIntelBot.py", line 176, in clean_up_and_close
    sys.exit(0)
SystemExit: 0

**Comment by oabsixr** [comment]
looks like its caused by a space in Google's most recent post: 
https://security.googleblog.com/2023/08/Announcing-Googles-Open-Source-Software-Vulnerability-Rewards-Program**_%20_**.html

the RSS feed returns it as a space with url encoding it, and the webhook doesn't handle the space well.

quick-fix by including urlencode in Formatting.py (may not be most elegant unfortunately, also doesn't fix the space in the)
in line 4, add:

`import urllib`

further down in line 44

change:
            `url=article["link"],`
to 
            `url=urllib.parse.unquote(urllib.parse.quote_plus(article["link"])),`

in line 54

change:
        `message.add_field(name=description, value=article["link"], inline=False)`


to
        `message.add_field(name=description, value=urllib.parse.unquote(urllib.parse.quote_plus(article["link"])), inline=False)`

**Comment by vxunderground** [comment]
User has not replied. Closing ticket.
